### ISSUE TITLE
引用全局变量失败

### ISSUE THREAD

**Issue by lihuacai168** [yinquanwang/FasterRunner#16]
1. 全局变量url已经定义
 2. 在编写api时,通过$url来调用,但是无法调用
![image](https://user-images.githubusercontent.com/11568297/50631517-8baaca80-0f7f-11e9-91af-f90877eefc09.png)
![image](https://user-images.githubusercontent.com/11568297/50631431-2e167e00-0f7f-11e9-9f47-14fac11c5a69.png)
![image](https://user-images.githubusercontent.com/11568297/50631448-3e2e5d80-0f7f-11e9-8cd4-ee5feb90ab7a.png)

**Comment by yinquanwang** [comment]
已修复
